import unittest
import sys
from types import SimpleNamespace
from unittest.mock import patch

from src.clipboard_paste import (
    AUTOGENERATED_TYPE,
    CONCEALED_TYPE,
    TOKEN_TYPE,
    TRANSIENT_TYPE,
    PasteboardSnapshot,
    paste_text_preserving_clipboard,
    post_paste_shortcut,
)


class _FakeItem:
    def __init__(self):
        self.values = {}

    @classmethod
    def alloc(cls):
        return cls()

    def init(self):
        return self

    def types(self):
        return list(self.values)

    def dataForType_(self, type_name):
        value = self.values.get(type_name)
        return value.encode() if isinstance(value, str) else value

    def setData_forType_(self, value, type_name):
        self.values[type_name] = bytes(value)
        return True

    def setString_forType_(self, value, type_name):
        self.values[type_name] = value
        return True


class _FakeData:
    @staticmethod
    def dataWithBytes_length_(payload, length):
        return bytes(payload[:length])


class _FakePasteboard:
    def __init__(self, items=None):
        self.items = list(items or [])

    def pasteboardItems(self):
        return self.items

    def clearContents(self):
        self.items = []

    def writeObjects_(self, items):
        self.items = list(items)
        return True

    def stringForType_(self, type_name):
        if not self.items:
            return None
        value = self.items[0].values.get(type_name)
        return value if isinstance(value, str) else None


class ClipboardPasteTests(unittest.TestCase):
    def appkit(self):
        return object, _FakeItem, "public.utf8-plain-text", _FakeData

    def test_private_paste_is_marked_and_original_formats_are_restored(self):
        original = _FakeItem()
        original.values = {
            "public.utf8-plain-text": "原剪贴板".encode(),
            "public.rtf": b"rtf",
        }
        board = _FakePasteboard([original])
        seen = {}

        def paste():
            seen.update(board.items[0].values)

        with (
            patch("src.clipboard_paste._appkit", side_effect=self.appkit),
            patch("src.clipboard_paste.time.sleep", return_value=None),
        ):
            self.assertTrue(
                paste_text_preserving_clipboard("语音结果", pasteboard=board, post_paste=paste)
            )

        self.assertIn(TRANSIENT_TYPE, seen)
        self.assertIn(CONCEALED_TYPE, seen)
        self.assertIn(AUTOGENERATED_TYPE, seen)
        self.assertNotIn(TOKEN_TYPE, board.items[0].values)
        self.assertEqual(
            board.items[0].values["public.utf8-plain-text"], "原剪贴板".encode()
        )
        self.assertEqual(board.items[0].values["public.rtf"], b"rtf")

    def test_private_paste_waits_for_pasteboard_visibility_before_shortcut(self):
        original = _FakeItem()
        original.values = {"public.utf8-plain-text": "旧内容".encode()}
        board = _FakePasteboard([original])
        sleeps = []

        with (
            patch("src.clipboard_paste._appkit", side_effect=self.appkit),
            patch("src.clipboard_paste.time.sleep", side_effect=sleeps.append),
        ):
            self.assertTrue(
                paste_text_preserving_clipboard(
                    "语音结果",
                    pasteboard=board,
                    before_paste_seconds=0.04,
                    settle_seconds=0.85,
                    post_paste=lambda: None,
                )
            )

        self.assertEqual(sleeps, [0.04, 0.85])

    def test_new_user_clipboard_wins_over_restoration(self):
        original = _FakeItem()
        original.values = {"public.utf8-plain-text": "旧内容".encode()}
        board = _FakePasteboard([original])

        def user_copies_during_paste():
            new_item = _FakeItem()
            new_item.values = {"public.utf8-plain-text": "用户刚复制".encode()}
            board.items = [new_item]

        with (
            patch("src.clipboard_paste._appkit", side_effect=self.appkit),
            patch("src.clipboard_paste.time.sleep", return_value=None),
        ):
            self.assertTrue(
                paste_text_preserving_clipboard(
                    "语音结果", pasteboard=board, post_paste=user_copies_during_paste
                )
            )

        self.assertEqual(
            board.items[0].values["public.utf8-plain-text"], "用户刚复制".encode()
        )

    def test_paste_shortcut_uses_combined_session_command_v(self):
        posted = []
        quartz = SimpleNamespace(
            CGEventSourceCreate=lambda state: ("source", state),
            CGEventCreateKeyboardEvent=lambda _source, keycode, down: {
                "keycode": keycode,
                "down": down,
            },
            CGEventSetFlags=lambda event, flags: event.update(flags=flags),
            CGEventPost=lambda tap, event: posted.append((tap, event.copy())),
            kCGEventFlagMaskCommand=8,
            kCGEventSourceStateCombinedSessionState=1,
            kCGSessionEventTap=2,
        )
        with patch.dict(sys.modules, {"Quartz": quartz}):
            post_paste_shortcut()

        self.assertEqual(
            [(tap, event["keycode"], event["down"], event["flags"]) for tap, event in posted],
            [(2, 9, True, 8), (2, 9, False, 8)],
        )


if __name__ == "__main__":
    unittest.main()
