"""Compatibility-first macOS paste with lossless clipboard restoration."""

from __future__ import annotations

import threading
import time
import uuid
from dataclasses import dataclass

from .utils.logger import logger


TRANSIENT_TYPE = "org.nspasteboard.TransientType"
CONCEALED_TYPE = "org.nspasteboard.ConcealedType"
AUTOGENERATED_TYPE = "org.nspasteboard.AutoGeneratedType"
RESTORED_TYPE = "org.nspasteboard.RestoredType"
SOURCE_TYPE = "org.nspasteboard.source"
TOKEN_TYPE = "com.wjcdev.veyqa.private-paste-token"
SOURCE_BUNDLE_ID = "com.wjcdev.veyqa"


@dataclass(frozen=True)
class PasteboardSnapshot:
    """Every pasteboard item and representation, retained only in memory."""

    items: tuple[tuple[tuple[str, bytes], ...], ...]


_paste_lock = threading.RLock()


def _appkit():
    from AppKit import NSPasteboard, NSPasteboardItem, NSPasteboardTypeString
    from Foundation import NSData

    return NSPasteboard, NSPasteboardItem, NSPasteboardTypeString, NSData


def capture_pasteboard(pasteboard) -> PasteboardSnapshot:
    captured: list[tuple[tuple[str, bytes], ...]] = []
    for item in pasteboard.pasteboardItems() or []:
        representations: list[tuple[str, bytes]] = []
        for type_name in item.types() or []:
            try:
                data = item.dataForType_(type_name)
                if data is not None:
                    representations.append((str(type_name), bytes(data)))
            except Exception as exc:  # noqa: BLE001
                logger.debug("跳过无法读取的剪贴板格式 %s: %s", type_name, exc)
        if representations:
            captured.append(tuple(representations))
    return PasteboardSnapshot(tuple(captured))


def _data(payload: bytes, nsdata):
    return nsdata.dataWithBytes_length_(payload, len(payload))


def place_private_text(pasteboard, text: str, token: str) -> None:
    _, item_type, string_type, nsdata = _appkit()
    item = item_type.alloc().init()
    item.setString_forType_(text, string_type)
    empty = _data(b"", nsdata)
    item.setData_forType_(empty, TRANSIENT_TYPE)
    item.setData_forType_(empty, CONCEALED_TYPE)
    item.setData_forType_(empty, AUTOGENERATED_TYPE)
    item.setString_forType_(SOURCE_BUNDLE_ID, SOURCE_TYPE)
    item.setString_forType_(token, TOKEN_TYPE)
    pasteboard.clearContents()
    if not pasteboard.writeObjects_([item]):
        raise RuntimeError("无法写入临时剪贴板")


def restore_pasteboard(pasteboard, snapshot: PasteboardSnapshot, token: str) -> bool:
    """Restore only if our temporary value is still current.

    If the user copies something during the paste window, their new clipboard
    wins and is never overwritten.
    """

    if pasteboard.stringForType_(TOKEN_TYPE) != token:
        logger.info("粘贴期间剪贴板已由其他应用更新，保留用户的新内容")
        return False

    _, item_type, _, nsdata = _appkit()
    pasteboard.clearContents()
    if not snapshot.items:
        return True

    restored_items = []
    for representations in snapshot.items:
        item = item_type.alloc().init()
        for type_name, payload in representations:
            item.setData_forType_(_data(payload, nsdata), type_name)
        # Clipboard-history apps that understand the common convention should
        # not record restoration as a new duplicate entry.
        empty = _data(b"", nsdata)
        item.setData_forType_(empty, TRANSIENT_TYPE)
        item.setData_forType_(empty, RESTORED_TYPE)
        restored_items.append(item)
    if not pasteboard.writeObjects_(restored_items):
        raise RuntimeError("无法恢复原剪贴板")
    return True


def post_paste_shortcut() -> None:
    from Quartz import (
        CGEventCreateKeyboardEvent,
        CGEventPost,
        CGEventSetFlags,
        CGEventSourceCreate,
        kCGEventFlagMaskCommand,
        kCGEventSourceStateCombinedSessionState,
        kCGSessionEventTap,
    )

    source = CGEventSourceCreate(kCGEventSourceStateCombinedSessionState)
    key_down = CGEventCreateKeyboardEvent(source, 9, True)  # ANSI V
    key_up = CGEventCreateKeyboardEvent(source, 9, False)
    if key_down is None or key_up is None:
        raise RuntimeError("无法创建粘贴快捷键事件")
    CGEventSetFlags(key_down, kCGEventFlagMaskCommand)
    CGEventSetFlags(key_up, kCGEventFlagMaskCommand)
    CGEventPost(kCGSessionEventTap, key_down)
    CGEventPost(kCGSessionEventTap, key_up)


def paste_text_preserving_clipboard(
    text: str,
    *,
    settle_seconds: float = 0.25,
    before_paste_seconds: float = 0.04,
    pasteboard=None,
    post_paste=post_paste_shortcut,
) -> bool:
    """Paste text, then restore every available original representation.

    A short pre-paste delay is intentional.  Some native/custom editors (most
    notably WeChat's macOS composer) observe the pasteboard asynchronously and
    can otherwise receive ``⌘V`` before the temporary item is visible to them.
    """

    if not text:
        return False
    with _paste_lock:
        if pasteboard is None:
            pasteboard_type, _, _, _ = _appkit()
            pasteboard = pasteboard_type.generalPasteboard()
        snapshot = capture_pasteboard(pasteboard)
        token = uuid.uuid4().hex
        try:
            place_private_text(pasteboard, text, token)
            time.sleep(max(0.0, before_paste_seconds))
            post_paste()
            time.sleep(max(0.05, settle_seconds))
            return True
        finally:
            try:
                restore_pasteboard(pasteboard, snapshot, token)
            except Exception as exc:  # noqa: BLE001
                logger.error("恢复原剪贴板失败: %s", exc)
